language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - apt-get update 
  - apt-get install --yes -qq cmake python3 qt5-default
  - apt-get install --yes ruby-full
  - apt-get install --yes swig
  - update-alternatives --install /usr/bin/python python /usr/bin/python3 10


before_script:
  - mkdir build
  - cd build
  - cmake

script:
  - make -j8
  - make test
